config/routes.rb
PulseServer::Application.routes.draw do

  root :to => "devices#index"
  match "devices/datatable" => "devices#datatable", :as => 'table'

  resources :devices
  resources :folders
  

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :folder
  has_one :profile

  validates_presence_of :name, :description, :ip, :port, :folder_id
  validates_numericality_of :port, :greater_than => 0
    
  after_initialize :init

  def init 
    # Set some default values
    self.last_state ||= 0
    self.up_emails_sent ||= 0
    self.down_emails_sent ||= 0
    self.times_up ||= 0
    self.times_down ||= 0
    self.disabled ||= false
    self.last_checked ||= 5.minutes.ago
  end
  
  # Called from daemon - returns devices that need to be monitored now
  def self.to_be_checked
    Device.where("last_checked <= ?", 5.minutes.ago)
  end
  
  # Filter the results based on search terms
  def self.search(keyword, sort, folder)
    keyword ||= ''
    folder ||= ''
    results = []
    if folder == ''
      devices = Device.order("#{sort[:by]} #{sort[:dir]}")
    else
      devices = Device.where(:folder_id => folder).order("#{sort[:by]} #{sort[:dir]}")
    end
    devices.each do |device|
      if device.name.downcase =~ /.*#{keyword.downcase}.*/ or keyword.downcase =~ /.*#{device.name.downcase}.*/ or get_distance(keyword, device.name) <= 4 or
         device.ip.downcase =~ /.*#{keyword.downcase}.*/ or keyword.downcase =~ /.*#{device.ip.downcase}.*/
          results << device
      end
    end
    results
  end
  
  private
  # Levenshtein distance of two strings 
  def self.get_distance(s1 ,s2)
      m = Hash.new
      (s1.length + 1).times do |i|
        m.store([i,0], i)
      end
      (s2.length + 1).times do |i|
        m.store([0,i], i)
      end
      s2.length.times do |j|
        s1.length.times do |k|
          if (s1[k] == s2[j]) 
            m.store([k+1,j+1], m[[k,j]])
          else
            s = []
            s << m[[k, j]] << m[[k+1, j]] << m[[k, j+1]]
            m.store([k+1,j+1], s.min+1)
          end
        end
      end
      return m[[s1.length, s2.length]]
    end
  
 
   
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  validates_presence_of :name, :description
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def get_distance(s1 ,s2)
      m = Hash.new
      (s1.length + 1).times do |i|
        m.store([i,0], i)
      end
      (s2.length + 1).times do |i|
        m.store([0,i], i)
      end
      s2.length.times do |j|
        s1.length.times do |k|
          if (s1[k] == s2[j]) 
            m.store([k+1,j+1], m[[k,j]])
          else
            s = []
            s << m[[k, j]] << m[[k+1, j]] << m[[k, j+1]]
            m.store([k+1,j+1], s.min+1)
          end
        end
      end
      return m[[s1.length, s2.length]]
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @folders = Folder.all
    params[:sort] ||= {'by'=>'id', 'dir'=>'asc'}
    params[:search] ||= ""
    @devices = Device.search(params[:search], params[:sort], params[:folder])
    json_response = { 'sort' => { 'by' => 'id', 'dir' => 'asc' }, 'devices' => @devices}
    respond_to do |format|
      format.html
      format.json { render :json => json_response, :status => :ok }
    end
  end

  def new
    @device = Device.new
    @folders = Folder.all
  end
  def create
    @device = Device.new(params[:device])
    @folders = Folder.all
    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, :notice => "Device created!" }
        format.xml { render :xml => @device, :status => :created, :location => @device }
      else
        format.html { render "new" }
        format.xml { render :xml => @device.errors, :status => :unprocessable_entity }
      end
      
    end
  end
  
  def show
    @device = Device.find(params[:id])
    @uptime = (@device.times_up == 0 && @device.times_down == 0) ? 0 : (@device.times_up/(@device.times_up + @device.times_down))*100
  end

  def edit
    @device = Device.find(params[:id])
    @folders = Folder.all
  end
  def update
    @device = Device.find(params[:id])
    @device.last_checked = 5.minutes.ago
    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, :notice => "Device updated!" }
        format.xml { head :ok }
      else
        format.html { render 'edit' }
        format.xml { render :xml => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy
    redirect_to devices_path
  end
  
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  def index
    @folders = Folder.all
  end

  def new
    @folder = Folder.new
  end
  def create
    @folder = Folder.new(params[:folder])
    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, :notice => "Folder created!" }
        format.xml  { render :xml => @folder, :status => :created, :location => @folder }
      else
        format.html { render "new" }
        format.xml  { render :xml => @folder.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @folder = Folder.find(params[:id])
  end
  def update
    @folder = Folder.find(params[:id])
    respond_to do |format|
       if @folder.update_attributes(params[:folder])
         format.html { redirect_to @folder, :notice => "Folder Updated" }
         format.xml  { head :ok }
       else
         format.html { render 'edit' }
         format.xml  { render :xml => @folder.errors, :status => :unprocessable_entity }
       end
    end
   
  end

  def show
    @folder = Folder.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper

end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/devices/_device.html.erb
<div class="device">
	<td><%= device.name %></td>
	<td><%= device.ip %></td>
	<td><%= device.port %></td>
	<td><%= device.last_state %></td>
	<td><%= ((device.times_up)/(device.times_down + device.times_up))*100 %></td>
</div>

app/views/devices/_device_form.html.erb
<%= form_for @device do |f| %>
	<% if @device.errors.any? %>
	  <div id="errorExplanation">
		<h2><%= pluralize(@device.errors.count, "error") %> prohibited this from being saved:</h2>
		<ul>
		<% @device.errors.full_messages.each do |msg| %>
		  <li><%= msg %></li>
		<% end %>
		</ul>
	  </div>
   	<% end %>
  <div class="field">
  	<%= f.label :name %><br />
  	<%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :description %><br />
  	<%= f.text_area :description %>
  </div>
  <div class="field">
  	<%= f.label :ip %><br />
  	<%= f.text_field :ip %>
  </div>
  <div class="field">
  	<%= f.label :port %><br />
  	<%= f.text_field :port %>
  </div>
  <div class="field">
  	<%= f.label :folder_id, "Folder" %>
	<%= f.select( :folder_id, options_from_collection_for_select(@folders, 'id', 'name') ) %>
  </div>
  <%= submit_tag submit_text %>
<% end %>

app/views/devices/edit.html.erb
<h1>Edit Device</h1>
<%= render :partial => 'device_form', :locals => {:submit_text => "Update"} %>
<%= link_to "Destroy", @device, :confirm => "Are you sure?", :method => 'delete' %>

app/views/devices/index.html.erb
<h1>Devices</h1><br />
<div id="search">
  Search: <input type="text" name="search_field" id="search_field" />
  <span id="search_message"></span>
  <span id="folder_sort">View by folder: <%= select("folder", "id", options_from_collection_for_select(@folders, 'id', 'name'), {:include_blank => true}, :id => 'folder_view') %></span>

</div>
<table id='devices'>
  <tr>
    <th>Name</th>
    <th>IP Address</th>
    <th>Port</th>
    <th>State</th>
    <th>Last Checked</th>
  </tr>
  <% @devices.each do |device| %>
    <tr id="<%= dom_id(device) %>" class="<%= device.last_state ? 'up' : 'down' %>">
      <td class="name"><%= device.name %></td>
      <td class="ip"><%= device.ip %></td>
      <td class="port"><%= device.port %></td>
  	  <td class="last_state"><%= device.last_state %></td>
  	  <td class="last_checked"><%= device.last_checked %></td>
  	  <td width="30"><%= link_to "Edit", edit_device_path(device) %></td>
    </tr>
  <% end %>
</table>
<span id="device_page"></span>

app/views/devices/new.html.erb
<h1>New Device</h1>
<%= render :partial => 'device_form', :locals => {:submit_text => "Create"} %>

app/views/devices/show.html.erb
<h1>Device</h1>
<p>Name: <%= @device.name %></p>
<p>Description: <%= @device.description %></p>
<p>IP: <%= @device.ip %></p>
<p>Port: <%= @device.port %></p>
<p>Last State: <%= @device.last_state %></p>
<p>Last Checked: <%= (Time.now - @device.last_checked).round/60 %> minutes ago</p>
<p># Times Up: <%= @device.times_up %></p>
<p>% Uptime: <%= @uptime %></p>

app/views/folders/_folder_form.html.erb
<%= form_for @folder do |f| %>
	<% if @folder.errors.any? %>
	  <div id="errorExplanation">
		<h2><%= pluralize(@folder.errors.count, "error") %> prohibited this from being saved:</h2>
		<ul>
		<% @folder.errors.full_messages.each do |msg| %>
		  <li><%= msg %></li>
		<% end %>
		</ul>
	  </div>
   	<% end %>
  <div class="field">
  	<%= f.label :name %><br />
  	<%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :description %><br />
  	<%= f.text_area :description %>
  </div>
  <%= submit_tag submit_text %>
<% end %>

app/views/folders/edit.html.erb
<h1>Edit Folder</h1>
<%= render :partial => 'folder_form', :locals => { :submit_text => "Update" } %>

app/views/folders/index.html.erb
<h1>Folders</h1>
<% @folders.each do |folder| %>
	<hr>
	<p>Name: <%= folder.name %></p>
	<p>Description: <%= folder.description %>
<% end %>

app/views/folders/new.html.erb
<h1>New Folder</h1>
<%= render :partial => 'folder_form', :locals => { :submit_text => "Create" } %>

app/views/folders/show.html.erb
<h1>Folder</h1>
<p>Name: <%= @folder.name %></p>
<p>Description: <%= @folder.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PulseServer</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>

</head>
<body>
	<div id="header">
		<div class="text"><p>Device Management Portal</p></div>
		<div class="button_holder">
			<%= link_to("Add Folder", new_folder_path, :class => "button") %>
			<%= link_to("Add Device", new_device_path, :class => "button") %>
			<%= link_to("All Devices", devices_path, :class => "button") %>
		</div>
	</div>

	<% if notice %>
		<div class="notice"><%= notice %></div>
	<% end %>
	<div id="content">
		<%= yield %>
	</div>	
</body>
</html>